import { StudentInfo } from '@/components/StudentList/type';

const studentInfo: Array<StudentInfo> = [
  {
    id: 1,
    name: '爱丽丝',
    avatar: '/images/roles/Alice.png',
    birthday: '3月25日',
    introduce: '是千年学院游戏开发部的爱丽丝',
    kizunaRank: 100,
    school: '千年科学学院',
    club: '游戏开发部',
    age: '??',
    height: '152',
    interest: '游戏（特别是RPG）',
    design: 'DoReMi',
    illustration: 'DoReMi',
    cv: '田中美海',
  },
  {
    id: 2,
    name: '阿罗娜',
    avatar: '/images/roles/Arona.png',
    birthday: '未知',
    introduce: '今日也多多指教',
    kizunaRank: 100,
    school: '夏莱',
    club: '',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 3,
    name: '阿露',
    avatar: '/images/roles/Aru.png',
    birthday: '3月12日',
    introduce: '一日一恶',
    kizunaRank: 100,
    school: '格黑娜',
    club: '万事屋68',
    age: '16',
    height: '160',
    interest: '学习经营',
    design: 'DoReMi',
    illustration: 'DoReMi',
    cv: '近藤玲奈',
  },
  {
    id: 4,
    name: '梓',
    avatar: '/images/roles/Azusa.png',
    birthday: '12月26日',
    introduce: 'et omnia vanitas',
    kizunaRank: 100,
    school: '圣三一综合学院',
    club: '补习授业部',
    age: '16',
    height: '149',
    interest: '无',
    design: 'NAMYO',
    illustration: 'NAMYO',
    cv: '种田梨纱',
  },
  {
    id: 5,
    name: '日富美',
    avatar: '/images/roles/Hifumi.png',
    birthday: '11月27日',
    introduce: '',
    kizunaRank: 100,
    school: '圣三一综合学院',
    club: '补习授业部',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 6,
    name: '日奈',
    avatar: '/images/roles/Hina.png',
    birthday: '2月19日',
    introduce: '',
    kizunaRank: 100,
    school: '格黑娜',
    club: '风纪委员会',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 7,
    name: '春奈',
    avatar: '/images/roles/Haruna.png',
    birthday: '3月1日',
    introduce: '',
    kizunaRank: 100,
    school: '格黑娜',
    club: '美食研究会',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 8,
    name: '星野',
    avatar: '/images/roles/Hoshino.png',
    birthday: '1月2日',
    introduce: '',
    kizunaRank: 100,
    school: '阿比多斯',
    club: '对策委员会',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 9,
    name: '泉奈',
    avatar: '/images/roles/Izuna.png',
    birthday: '12月16日',
    introduce: '',
    kizunaRank: 100,
    school: '百鬼夜行联合学院',
    club: '忍术研究部',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 10,
    name: '小春',
    avatar: '/images/roles/Koharu.png',
    birthday: '4月16日',
    introduce: '禁止色色！',
    kizunaRank: 100,
    school: '圣三一综合学院',
    club: '补习授业部',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 11,
    name: '末花',
    avatar: '/images/roles/Mika.png',
    birthday: '5月8日',
    introduce: '正在招集可以一起说话的人！',
    kizunaRank: 100,
    school: '圣三一综合学院',
    club: '茶话会',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 12,
    name: '梓（泳装）',
    avatar: '/images/roles/Azusa_mizugi.png',
    birthday: '12月26日',
    introduce: '',
    kizunaRank: 100,
    school: '圣三一综合学院',
    club: '补习授业部',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 13,
    name: '伊吕波',
    avatar: '/images/roles/Iroha.png',
    birthday: '11月16日',
    introduce: '看书中，如果不是要事请勿联系',
    kizunaRank: 100,
    school: '格黑娜',
    club: '万魔殿',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 14,
    name: '和纱',
    avatar: '/images/roles/Kazusa.png',
    birthday: '8月5日',
    introduce: '是放学后甜点部的成员',
    kizunaRank: 100,
    school: '圣三一综合学院',
    club: '放学后甜点部',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 15,
    name: '美游',
    avatar: '/images/roles/Miyu.png',
    birthday: '7月12日',
    introduce: '前方一片黑暗……',
    kizunaRank: 100,
    school: 'SRT特殊学院',
    club: 'RABBIT小队',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },

  {
    id: 16,
    name: '桃井',
    avatar: '/images/roles/Momoi.png',
    birthday: '12月8日',
    introduce: '游戏控！',
    kizunaRank: 100,
    school: '千年科学学院',
    club: '游戏开发部',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 17,
    name: '睦月',
    avatar: '/images/roles/Mutsuki.png',
    birthday: '7月29日',
    introduce: '有没有什么有趣的事情呢~',
    kizunaRank: 100,
    school: '格黑娜',
    club: '便利屋68',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 18,
    name: '若藻',
    avatar: '/images/roles/Wakamo.png',
    birthday: '4月3日',
    introduce: '我一直都会在老师的身边……❤',
    kizunaRank: 100,
    school: '百鬼夜行联合学院',
    club: '无',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
  {
    id: 19,
    name: '柚子',
    avatar: '/images/roles/Yuzu.png',
    birthday: '8月12日',
    introduce: '404 Not Found',
    kizunaRank: 100,
    school: '千年科学学院',
    club: '游戏开发部',
    age: '',
    height: '',
    interest: '',
    design: '',
    illustration: '',
    cv: '',
  },
];

export default studentInfo;
